<script setup lang="ts">
useSeoMeta({
  title: "Terms of Service | NEXORA.AI",
  description:
    "Terms of Service and API usage agreement for NEXORA AI platform services.",
});

const effectiveDate = "September 24, 2026";
</script>

<template>
  <div
    class="min-h-screen bg-[#070b14] text-white mt-10 py-16 px-6 relative overflow-hidden"
  >
    <!-- Ambient Background Glow -->
    <div
      class="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-96 bg-primary/10 blur-[120px] pointer-events-none -z-10"
    />

    <div class="max-w-4xl mx-auto space-y-10">
      <!-- Top Navigation / Breadcrumb -->
      <div
        class="flex items-center justify-between border-b border-white/10 pb-6"
      >
        <NuxtLink
          to="/"
          class="inline-flex items-center gap-2 text-xs font-mono text-gray-400 hover:text-white transition-colors"
        >
          <span>←</span> Back to Home
        </NuxtLink>
        <span class="text-xs font-mono text-gray-500">
          EFFECTIVE DATE: {{ effectiveDate }}
        </span>
      </div>

      <!-- Page Header -->
      <div class="space-y-3">
        <span
          class="inline-block px-3 py-1 rounded-full text-xs font-mono font-semibold bg-primary/10 text-primary border border-primary/20"
        >
          INFRASTRUCTURE AGREEMENT
        </span>
        <h1
          class="text-3xl md:text-4xl font-bold font-mono tracking-tight text-white"
        >
          Terms of Service
        </h1>
        <p class="text-gray-400 text-sm leading-relaxed max-w-2xl">
          Rules, operational boundaries, and API SLA terms governing the
          NEXORA.AI autonomous engine.
        </p>
      </div>

      <!-- Content Sections -->
      <div
        class="space-y-8 text-sm text-gray-300 leading-relaxed border-t border-white/10 pt-8"
      >
        <section class="space-y-3">
          <h2
            class="text-lg font-mono font-bold text-white flex items-center gap-2"
          >
            <span class="text-primary">01.</span> Acceptance of Terms
          </h2>
          <p>
            By accessing or integrating NEXORA.AI APIs, SDKs, or cloud agent
            infrastructure, you agree to be bound by these Terms of Service. If
            you are entering into this agreement on behalf of an enterprise
            entity, you represent that you have authority to bind that entity.
          </p>
        </section>

        <section class="space-y-3">
          <h2
            class="text-lg font-mono font-bold text-white flex items-center gap-2"
          >
            <span class="text-primary">02.</span> Acceptable Use Policy (AUP)
          </h2>
          <p>
            You agree not to deploy autonomous agents through NEXORA.AI for any
            unauthorized or harmful actions, including but not limited to:
          </p>
          <ul
            class="list-disc list-inside space-y-1.5 text-gray-400 pl-2 font-mono text-xs"
          >
            <li>
              Attempting unauthorized penetration or vulnerability scanning of
              external networks
            </li>
            <li>
              Generating automated malicious code or automated exploitation
              vectors
            </li>
            <li>
              Bypassing rate limits, API quotas, or system security isolation
              mechanisms
            </li>
            <li>
              Executing non-compliant financial or identity manipulation scripts
            </li>
          </ul>
        </section>

        <section class="space-y-3">
          <h2
            class="text-lg font-mono font-bold text-white flex items-center gap-2"
          >
            <span class="text-primary">03.</span> Intellectual Property & Output
            Ownership
          </h2>
          <p>
            All custom workflows, pipeline definitions, code, and structured
            outputs generated by your autonomous agent workloads remain your
            exclusive intellectual property. NEXORA.AI retains ownership of the
            underlying framework, runtime engines, and proprietary node
            architecture.
          </p>
        </section>

        <section class="space-y-3">
          <h2
            class="text-lg font-mono font-bold text-white flex items-center gap-2"
          >
            <span class="text-primary">04.</span> Service Levels & Availability
          </h2>
          <p>
            NEXORA.AI targets a 99.9% uptime commitment for Enterprise tier
            infrastructure nodes. Planned maintenance windows are communicated
            at least 48 hours in advance via our network status protocol.
          </p>
        </section>

        <section class="space-y-3">
          <h2
            class="text-lg font-mono font-bold text-white flex items-center gap-2"
          >
            <span class="text-primary">05.</span> Limitation of Liability
          </h2>
          <p>
            NEXORA.AI provides agent infrastructure "as is." Under no
            circumstances shall NEXORA.AI be liable for indirect, incidental, or
            consequential damages resulting from autonomous agent decision
            outputs or third-party service downtime.
          </p>
        </section>

        <section class="space-y-3">
          <h2
            class="text-lg font-mono font-bold text-white flex items-center gap-2"
          >
            <span class="text-primary">06.</span> Legal Contact
          </h2>
          <p>
            For legal inquiries, contract amendments, or enterprise custom SLA
            requests, contact:
          </p>
        </section>
      </div>
    </div>
  </div>
</template>
